baseURL = "https://wnynas.com"
title = "WNYNAS"
author = "SiloCityLabs"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-6WF8VRZK5X"

# Disqus Comment System
#disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[renderer]
  unsafe = true

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/server.png"
    alt = "WNYNAS"
    text = "WNYNAS"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "WNYNAS" 

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_og_title = "WNYNAS"
    meta_og_type = "website"
    meta_og_url = "https://wnynas.com"
    meta_og_image = ""
    meta_og_description = ""
    meta_description = ""

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 2

  [[menu.footer]]
    name = "Terms of Service"
    url = "/terms"
    weight = 3

  [[menu.footer]]
    name = "Contact Us"
    # pre = "<i class='fas fa-envelope text-2xl'></i>"
    url = "/contact"
    weight = 4

